name: CI

on:
  - pull_request

jobs:
  build:
    name: Build
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            arch: amd64
          - os: ubuntu-24.04
            arch: amd64
          - os: ubuntu-24.04
            arch: arm64
          - os: windows-2022
            arch: x64
          - os: macos-13
            arch: x64
          - os: macos-14
            arch: arm64

    runs-on: ${{ matrix.arch == 'arm64' && matrix.os == 'ubuntu-24.04' && 'ubuntu-24.04-arm64' || matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Install Rust toolchain
        run: |
          rustup update
          rustup show
      - name: install Just
        uses: extractions/setup-just@v1
        with:
          just-version: 1.14.0
      - name: Build and Test
        run: just ci
